### ISSUE TITLE
GitHub Action exceeds 75% usage in private repository

### ISSUE THREAD

**Issue by hieuwu** [suesitran/just-for-fun#1]
**Summary**:
I tried the code from this to make my contribution chart more green as a private repository . Unfortunately, I received this email said that my usage of Github Action exceeded 75%.
![92EA43CA-92C2-405D-BC66-20BC3B0CF6A9](https://user-images.githubusercontent.com/43868345/209456214-ceb589fe-0906-4aef-8477-0843974f6225.png)

**Conclusion**:
If you guys try this code, please make sure your repository is Public and configure mindfully the frequency of commits per day. Be careful of the black magic power 😂

**Comment by suesitran** [comment]
yup agree 😂 for private repo, you only have 3000 minutes per month, and this action will eat up those minutes in no time 😂
